apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-dynamodb-access
      containers:
        - name: backend
          image: 391970746680.dkr.ecr.ap-southeast-2.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_DEFAULT_REGION
              value: ap-southeast-2
            - name: DYNAMODB_TABLE_NAME
              value: messages
